// Code generated by mockery v1.1.0. DO NOT EDIT.

package mocks

import (
	"github.com/mhogar/migrationrunner"
	"github.com/stretchr/testify/mock"
)

// MigrationRepository is an autogenerated mock type for the MigrationRepository type
type MigrationRepository struct {
	mock.Mock
}

// GetMigrations provides a mock function with given fields:
func (_m *MigrationRepository) GetMigrations() []migrationrunner.Migration {
	ret := _m.Called()

	var r0 []migrationrunner.Migration
	if rf, ok := ret.Get(0).(func() []migrationrunner.Migration); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]migrationrunner.Migration)
		}
	}

	return r0
}
